name: Build and Deploy Docusaurus (Strict FTPS)

on:
  push:
    branches: [ main ]

concurrency:
  group: docusaurus-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Deploy via FTPS (implicit, strict)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ${{ secrets.FTP_HOST }}     # HOSTNAME, not IP
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        protocol: ftps-legacy               # implicit FTPS
        port: 990
      security: strictname: Build and Deploy Docusaurus (Strict FTPS)

on:
  push:
    branches: [ main ]

concurrency:
  group: docusaurus-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Deploy via FTPS (implicit, strict)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}       # 👈 hostname, not IP
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}

          protocol: ftps-legacy                  # 👈 implicit FTPS
          port: 990
          security: strict                       # 👈 keep strict TLS validation

          local-dir: ./build/                    # must end with /
          server-dir: ${{ secrets.FTP_SERVER_DIR }} # 👈 secret, must end with /

          log-level: verbose
          timeout: 120000


    local-dir: ./build/
    server-dir: ${{ secrets.FTP_SERVER_DIR }}

    log-level: verbose
    timeout: 120000
